### ISSUE TITLE
Upload to nuget.org

### ISSUE THREAD

**Issue by kamikos** [Marcel-Baumgartner/SharpNetCraft#1]
Any chance for uploading this to nuget?
Tried compiling it myself but got 3k errors instead

**Comment by Masu-Baumgartner** [comment]
I recommend to use the dll in the relaese tab.
Maybe i will upload this to nuget when im finished with developing.

**Comment by Masu-Baumgartner** [comment]
If you want it to compile it your own, you have to use DotNet Core.
